# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KosztMapy
                                 A QGIS plugin
 Oblicza prawdopodobny koszt zamawianej mapy zasadniczej
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-11
        copyright            : (C) 2022 by Grzegorz Warszycki
        email                : opti33@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KosztMapy class from file KosztMapy.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .koszt_mapy import KosztMapy
    return KosztMapy(iface)
